# Generated by Django 3.1.7 on 2021-03-02 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_deal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='deal',
            new_name='promotion',
        ),
    ]
