# Generated by Django 3.1.7 on 2021-03-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210302_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='scent',
            field=models.CharField(max_length=50),
        ),
    ]
