# Generated by Django 3.1.7 on 2021-03-02 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210302_1235'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deal',
            field=models.BooleanField(default=False),
        ),
    ]
